name: wuai_ocr_app
description: WUAiOCR
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  permission_handler: ^10.4.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  ffi: ^2.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true