name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy onnxtr Pillow setuptools

      - name: Build Python bridge
        run: |
          cd python
          python build.py
          
          # Debug output
          echo "Listing built files:"
          find . -name "*.so"
          
          # Create Android library directories
          mkdir -p ../android/app/src/main/jniLibs/arm64-v8a
          mkdir -p ../android/app/src/main/jniLibs/armeabi-v7a
          mkdir -p ../android/app/src/main/jniLibs/x86_64
          
          # Find the most recently built .so file
          LATEST_SO=$(find . -name "*.so" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
          
          if [ -n "$LATEST_SO" ] && [ -f "$LATEST_SO" ]; then
            echo "Found library at: $LATEST_SO"
            cp "$LATEST_SO" ../android/app/src/main/jniLibs/arm64-v8a/libocr_bridge.so
            cp "$LATEST_SO" ../android/app/src/main/jniLibs/armeabi-v7a/libocr_bridge.so
            cp "$LATEST_SO" ../android/app/src/main/jniLibs/x86_64/libocr_bridge.so
            echo "Library copied successfully"
          else
            echo "Failed to find built library"
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3          

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2        

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties

      - name: Make Gradlew Executable
        run: chmod +x android/gradlew

      - name: Ensure AndroidX is enabled
        run: |
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
                    
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Clean Gradle
        run: cd android && ./gradlew clean        

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk