name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Build Python bridge
        run: |
          cd python
          python build.py
          
          # Create Android library directories
          mkdir -p ../android/app/src/main/jniLibs/arm64-v8a
          mkdir -p ../android/app/src/main/jniLibs/armeabi-v7a
          mkdir -p ../android/app/src/main/jniLibs/x86_64
          
          # Copy the built library to Android directories
          LIB_PATH=$(find . -name "ocr_bridge*.so")
          if [ -n "$LIB_PATH" ]; then
            cp "$LIB_PATH" ../android/app/src/main/jniLibs/arm64-v8a/libocr_bridge.so
            cp "$LIB_PATH" ../android/app/src/main/jniLibs/armeabi-v7a/libocr_bridge.so
            cp "$LIB_PATH" ../android/app/src/main/jniLibs/x86_64/libocr_bridge.so
          else
            echo "Failed to find built library"
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk